apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gym-log-book
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("gym.british-information-technologies.org") && PathPrefix("/rpc")
      kind: Rule
      priority: 20
      services:
        - name: gym-log-book-server-traffic
          kind: TraefikService
          namespace: gym-log-book
    - match: Host("gym.british-information-technologies.org") && PathPrefix("/")
      kind: Rule
      priority: 10
      services:
        - name: gym-log-book-web-traffic
          kind: TraefikService
          namespace: gym-log-book
  tls:
    secretName: gym-log-book-tls
