apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gym-log-book

resources:
  - ../../base
  - certificate.yaml
  - ingress.yaml
  - ingressroute.yaml
  - traefik-services.yaml

patches:
  - path: rollout-patches.yaml
  - path: image-patches.yaml
