[versions]
android_version = "8.9.1"
composeBomVersion = "2025.04.00"
kotlin_android_version = "1.9.22"
hilt_version = "2.56.1"
crypto_version = "1.0.0"
lifecycleRuntimeKtxVersion = "2.8.7"
materialIconsExtendedVersion = "1.7.8"
material_version = "1.12.0"
serialisation_plugin_version = "2.1.10"
compose_version = "2.0.21"

android_kotlin_core_version = "1.16.0"
android_appcompat_version = "1.7.0"
android_constraint_layout_version = "2.2.1"

datetime_version = "0.6.2"

hiltAndroidVersion = "2.56.1"
hiltNavigationComposeVersion = "1.2.0"

jbcryptVersion = "0.4"

navigation_version = "2.8.9"

room_version = "2.7.0"

json_serialisation_version = "1.8.1"


nav_version = "2.8.9"
gson_version = "2.9.0"
work_version = "2.10.0"
security_version = "1.0.0"
workRuntimeVersion = "2.10.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android_appcompat_version" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "android_constraint_layout_version" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "android_kotlin_core_version" }

android-crypto = { module = "androidx.security:security-crypto", version.ref = "crypto_version" }

livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx" }
lifecycle-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-livedata = { module = "androidx.compose.runtime:runtime-livedata" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
compose-activity = { module = "androidx.activity:activity-compose" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime_version" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidVersion" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidVersion" }

jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcryptVersion" }

material = { module = "com.google.android.material:material", version.ref = "material_version" }
compose-material = { module = "androidx.compose.material:material" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtendedVersion" }

navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation_version" }
navigation-runtime = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigation_version" }

room-compiler = { module = "androidx.room:room-compiler", version.ref = "room_version" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room_version" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room_version" }

serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json_serialisation_version" }

work-manager = { module = "androidx.work:work-runtime", version.ref = "workRuntimeVersion" }

[bundles]
compose = ["compose-activity", "compose-ui", "compose-ui-graphics", "compose-ui-tooling-preview"]
hilt = ["hilt-android", "hilt-navigation"]
lifecycle = ["lifecycle-ktx", "androidx-livedata", "livedata-ktx"]
material-design = ["material", "compose-material", "compose-material3", "compose-material-icons-extended"]
navigation = ["navigation-compose", "navigation-runtime"]
room = ["room-runtime", "room-ktx"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android_version" }
android-library = { id = "com.android.library", version.ref = "android_version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_android_version" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt_version" }
serialisation = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialisation_plugin_version" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose_version" }