apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gym-log-book

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: gym-log-book

resources:
  - namespace.yaml
  - server-rollout.yaml
  - server-services.yaml
  - web-rollout.yaml
  - web-services.yaml
