apiVersion: v1
kind: Service
metadata:
  name: gym-log-book-server-stable
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: gym-log-book-server
---
apiVersion: v1
kind: Service
metadata:
  name: gym-log-book-server-preview
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: gym-log-book-server
