apiVersion: v1
kind: Service
metadata:
  name: gym-log-book-web-stable
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: gym-log-book-web
---
apiVersion: v1
kind: Service
metadata:
  name: gym-log-book-web-preview
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: gym-log-book-web
