apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gym-log-book-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/Gym_Log_Book.git
    targetRevision: master
    path: deploy/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: gym-log-book
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
