apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gym-log-book-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/external-url: https://gym.british-information-technologies.org
spec:
  project: default
  source:
    repoURL: https://github.com/michael-bailey/gym-log-book.git
    targetRevision: master
    path: deploy/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: gym-log-book
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
